### ISSUE TITLE
dcm-list-cm-accounts key error

### ISSUE THREAD

**Issue by zomGreg** [enStratus/mixcoatl#191]
```
➜  ~  dcm-list-cm-accounts
Traceback (most recent call last):
  File "/usr/local/bin/dcm-list-cm-accounts", line 4, in <module>
    __import__('pkg_resources').run_script('mixcoatl==0.10.32', 'dcm-list-cm-accounts')
  File "build/bdist.macosx-10.10-x86_64/egg/pkg_resources/__init__.py", line 652, in run_script

  File "build/bdist.macosx-10.10-x86_64/egg/pkg_resources/__init__.py", line 1573, in run_script

  File "/usr/local/lib/python2.7/site-packages/mixcoatl-0.10.32-py2.7.egg/EGG-INFO/scripts/dcm-list-cm-accounts", line 26, in <module>
    cm_system_name = cm_system[str(cma.cm_service['cm_system']['cm_system_id'])]
KeyError: 'cm_system'
```

**Comment by bdwilliams** [comment]
This utility no longer exists in the 0.10.* version of mixcoatl.
