### ISSUE TITLE
dcm-create-server '--budgetid' is not optional

### ISSUE THREAD

**Issue by igable** [enStratus/mixcoatl#220]
For example:

```
(mixcoatl)➜  mixcoatl  dcm-create-server --machineimage 29710 --datacenter 1273 --name igable-terminateme --productid t1.micro --description longstring
Traceback (most recent call last):
  File "/Users/igable/code/mixcoatl/bin/dcm-create-server", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/Users/igable/code/mixcoatl/mixcoatl/bin/dcm-create-server", line 53, in <module>
    result = new_server.launch()
  File "/Users/igable/code/mixcoatl/mixcoatl/mixcoatl/decorators/validations.py", line 18, in validate
    raise ValidationException('Required attribute "%s" is missing' % ra)
mixcoatl.decorators.validations.ValidationException: Required attribute "budget" is missing
```

It could be that the stack trace is enough for the user to figure out what's missing. However, for the cli tool I propose that if a mandatory field is missing that we handle the exception and tell the user what they need to add. Could fix this around [here](https://github.com/enStratus/mixcoatl/blob/a770962831db0cb4e4bdde69e2f8cc7a521595e2/bin/dcm-create-server#L42)

There might be a few more of these kicking around.

**Comment by igable** [comment]
closing in favor of #235
