### ISSUE TITLE
dcm-list-billing-codes : Request is not authorized

### ISSUE THREAD

**Issue by jimsander** [enStratus/mixcoatl#238]
Unable to list billing codes despite being associated with Administrator Group with role Admin (Full Access) in AWS Acme Account

User Details
- enstratusUserId	3250
- userId	p3448
- alphaName	Sander, Jim	

```
# dcm-list-billing-codes --csv
Traceback (most recent call last):
  File "/usr/local/bin/dcm-list-billing-codes", line 21, in <module>
    results = BillingCode.all()
  File "/Library/Python/2.7/site-packages/mixcoatl/admin/billing_code.py", line 131, in all
    raise BillingCodeException(r.last_error)
mixcoatl.admin.billing_code.BillingCodeException: A server error occurred processing your request: Request is not authorized
```

**Comment by igable** [comment]
@jimsander Are you using an account key or a user key? I confirm that I replicate this behavior with account key, but it works with a user key.

**Comment by jimsander** [comment]
Definitely an account key 'jdsAWSAcme';  I'll try a user key

**Comment by igable** [comment]
@jimsander can you confirm that you were able to do this with a user key

**Comment by jimsander** [comment]
Yes, a user key works (forgot to follow up here) 

# PASS (with User key)

```
# dcm-list-billing-codes
+------+---------------------+---------------+-------------+--------------+---------------+-----------------+--------+
| ID   | Name                | Budget Code   | Soft Quota  | Hard Quota   | Current Usage | Projected Usage | Status |
+------+---------------------+---------------+-------------+--------------+---------------+-----------------+--------+
| 5268 | 000-2224-9834       | 000-2224-9834 | USD 800.00  | USD 1000.00  | USD 0.00      | USD 0.00        | ACTIVE |
| 8619 | Chris Test Budget   | 1728304       |  0.00       | USD 2.00...

# echo $ES_ACCESS_KEY;  dcm-list-api-keys | grep $ES_ACCESS_KEY
OVCYCBPNSZIAHHSFHZDW
| ACTIVE   | 1210    | jdsAWSAcmeUser                  | User Key                                   | OVCYCBPNSZIAHHSFHZDW | False          | False            |
```

# FAIL with Account key (Also included api key list output)

```
# echo $ES_ACCESS_KEY; dcm-list-api-keys | grep $ES_ACCESS_KEY
FZPYWSZQTRFWFKTIGWFN
Traceback (most recent call last):
  File "/usr/local/bin/dcm-list-api-keys", line 27, in <module>
    results = ApiKey.all()
  File "/Library/Python/2.7/site-packages/mixcoatl/admin/api_key.py", line 195, in all
    raise ApiKeyException(r.last_error)
mixcoatl.admin.api_key.ApiKeyException: Listing API keys is currently supported only for user level keys.

# dcm-list-billing-codes
Traceback (most recent call last):
  File "/usr/local/bin/dcm-list-billing-codes", line 21, in <module>
    results = BillingCode.all()
  File "/Library/Python/2.7/site-packages/mixcoatl/admin/billing_code.py", line 131, in all
    raise BillingCodeException(r.last_error)
mixcoatl.admin.billing_code.BillingCodeException: A server error occurred processing your request: Request is not authorized

```

**Comment by bdwilliams** [comment]
Is there a way to derive whether a key is an account or user key from the API?  I have previously looked to see if a key was a customer or system key using:

```
from mixcoatl.admin.api_key import ApiKey
results = ApiKey.all(access_key=THE_ACCESS_KEY)
```

We could then catch/except the above calls that require a User key and return an error letting the user know.

**Comment by jimsander** [comment]
I noticed the output of `dcm-list-api-keys` has boolean fields for customer and system 

```
# dcm-list-api-keys | awk -F\| -v a=$ES_ACCESS_KEY '(NR <=3 || $6 ~ a) { print  $0 }'
+----------+---------+---------------------------------+--------------------------------------------+----------------------+----------------+------------------+
| State    | Account | Name                            | Description                                | Access Key           | Is System Key? | Is Customer Key? |
+----------+---------+---------------------------------+--------------------------------------------+----------------------+----------------+------------------+
| ACTIVE   | 1210    | jdsAWSAcmeUser                  | User Key                                   | OVCYCBPNSZIAHHSFHZDW | False          | False            |
```

**Comment by igable** [comment]
I think the fact that this doesn't work with a account key may be in a bug in the API. I will follow up. If this is in fact how this is supposed to work I'll catch it as Brian suggests.

**Comment by igable** [comment]
@rwfaulkner I believe this could be related to internal bug [FB-7442](https://enstratus.fogbugz.com/default.asp?7442) is there an easy way for you to check on that?

**Comment by igable** [comment]
There is now an internal bug filed on this [FB-7538](https://enstratus.fogbugz.com/default.asp?7538)

**Comment by igable** [comment]
FB-7538 is fixed. Confirmed with Mixcoatl 1.1.1. Closing.
