### ISSUE TITLE
 Again mixcoatl --version broken in 1.1.0

### ISSUE THREAD

**Issue by igable** [enStratus/mixcoatl#259]
:poop: Again somehow the checking against pypi for current versions broken when I uploaded a new release. I'm going to remove this feature until such a time that I can figure out how to test it :goberserk: BEFORE i upload.

```
(mixjunk)➜  ~  mixcoatl --version
Traceback (most recent call last):
  File "/usr/local/bin/mixcoatl", line 4, in <module>
    __import__('pkg_resources').require('mixcoatl==0.10.36')
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3084, in <module>
    @_call_aside
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3070, in _call_aside
    f(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3097, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 651, in _build_master
    ws.require(__requires__)
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 952, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 839, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'mixcoatl==0.10.36' distribution was not found and is required by the application
```

**Comment by igable** [comment]
I appear to trolling myself on this one. I had a a old `/usr/local/bin/mixcoatl` in my path before my virtualenv. :trollface:
