### ISSUE TITLE
dcm-create-account customer attribute crash

### ISSUE THREAD

**Issue by igable** [enStratus/mixcoatl#265]
@shaunsmarshall reported the following crash:

```
Shauns-MacBook-Pro:~ shaun$ dcm-create-account --account_name <snip> --cloud_id <snip> --account_number "<snip>" --api_key <snip>  --api_secret $api
Traceback (most recent call last):
  File "/usr/local/bin/dcm-create-account", line 30, in <module>
    result = a.add()
  File "/usr/local/lib/python2.7/site-packages/mixcoatl/decorators/validations.py", line 19, in validate
    return method(obj, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/mixcoatl/admin/account.py", line 159, in add
    if self.customer:
  File "/usr/local/lib/python2.7/site-packages/mixcoatl/decorators/lazy.py", line 53, in __get__
    return self._func(instance)
  File "/usr/local/lib/python2.7/site-packages/mixcoatl/admin/account.py", line 58, in customer
    return self.__customer
AttributeError: 'Account' object has no attribute '_Account__customer'
```

Looks like a problem with either CLI dcm-create-account having the customer flag commented for some reason, or not sufficiently checking for the existence of customer attribute on the account object. I furnished Shaun with a quick hack for this while a decent patch can be tested.

**Comment by igable** [comment]
@bdwilliams would you happen to recall why the customer flag got commented out would you [L13](https://github.com/enStratus/mixcoatl/blob/0f41a9949ce81e20337af848fe2e574fecaf1594/bin/dcm-create-account#L13). No worries if not.
