### ISSUE TITLE
dcm-update-group broken when only --name or --description used

### ISSUE THREAD

**Issue by igable** [enStratus/mixcoatl#274]
Results look like:

```
(mixcoatl)➜  .enstratius  dcm-update-group --group_id 201 --description "Hello Developers"
Traceback (most recent call last):
  File "/Users/igable/code/mixcoatl/bin/dcm-update-group", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/Users/igable/code/mixcoatl/mixcoatl/bin/dcm-update-group", line 32, in <module>
    result = group.updateDescription(group_description)
```

**Comment by igable** [comment]
Fixed in 837ba9dee97d815b914

This is an old camel vs snake case bug.
